version: '3.9'

services:

  database_mongo:
    container_name: mongo_container
    image: "mongo:4.4.7"
    hostname: mongo_db_host
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  flask:
    build: .
    container_name: flask_container
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./:/backend
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - database_mongo
    command: gunicorn server:app --reload -b 0.0.0.0:8000


networks:
  backend:
    external: false
    name: backend
